version: "3.7"
services:
  dev-mysql:
    container_name: dev-mysql
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1

  web-novel-redis:
    image: redis:alpine
    container_name: web-novel-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes